# Generated by Django 5.0.3 on 2024-03-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_user_avatar_comment_like_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='active_like',
        ),
        migrations.AddField(
            model_name='like',
            name='liked',
            field=models.BooleanField(default=True),
        ),
    ]
